apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    app: argocd
  ports:
    - protocol: TCP
      port: {{ .Values.argocd.server.servicePort }}
      targetPort: {{ .Values.argocd.server.servicePort }}
