apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: observation
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.grafana.image }}
        ports:
        - containerPort: {{ .Values.grafana.servicePort }}
