apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: observation
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: {{ .Values.grafana.servicePort }}
      targetPort: {{ .Values.grafana.servicePort }}
