apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: observation
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'webapp'
        static_configs:
          - targets: ['webapp-service.default.svc.cluster.local:30080']
      - job_name: 'mongodb'
        static_configs:
          - targets: ['mongodb-service.default.svc.cluster.local:27017']
      - job_name: 'jenkins'
        static_configs:
          - targets: ['jenkins-service.jenkins.svc.cluster.local:8080']
      - job_name: 'argocd'
        static_configs:
          - targets: ['argocd-server.argocd.svc.cluster.local:80']
