replicaCount: 1

webapp:
  replicaCount: 1
  image: artyom1996/gqwebapp
  containerPort: 5000
  servicePort: 30080

mongodb:
  replicaCount: 1
  image: mongo:latest
  rootUsername: admin
  rootPassword: admin
  storageSize: 10Gi
  mongoPort: 27017

jenkins:
  controller:
    serviceType: NodePort
    nodePort: 32000
    servicePort: 8080
    admin:
      username: admin
      password: Aa123456
    installPlugins:
      - kubernetes
      - workflow-aggregator
      - git
      - configuration-as-code
      - gitlab-plugin
      - blueocean
      - workflow-multibranch
      - login-theme
      - prometheus
      - github-oauth
    persistence:
      enabled: true
      size: 8Gi
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      paths:
        - path: /ci
          pathType: Prefix
          backend:
            service:
              name: gq-helm-test-jenkins
              port:
                number: 8080
      hosts:
        - guessquest
  namespaceOverride: jenkins
  agent:
    enabled: true
    image:
      repository: "artyom1996/my-jenkins-agent"
      tag: "latest"

ingress:
  enabled: true
  annotations: {}
  ingressClassName: nginx
  hosts:
    - host: guessquest
      paths:
        - path: /ci
          service:
            name: jenkins
            port: 8080
        - path: /monitor
          service:
            name: prometheus
            port: 9090
        - path: /observe
          service:
            name: grafana
            port: 3000
        - path: /database
          service:
            name: mongodb
            port: 27017
  tls: []
