replicaCount: 1

webapp:
  replicaCount: 1
  image: artyom1996/gqwebapp
  containerPort: 5000
  servicePort: 30081

mongodb:
  replicaCount: 1
  image: mongo:latest
  rootUsername: admin
  rootPassword: admin
  storageSize: 10Gi
  mongoPort: 27017

jenkins:
  controller:
    serviceType: NodePort
    nodePort: 32000
    servicePort: 8080
    admin:
      username: admin
      password: Aa123456
    installPlugins:
      - kubernetes
      - workflow-aggregator
      - git
      - configuration-as-code
      - gitlab-plugin
      - blueocean
      - workflow-multibranch
      - login-theme
      - prometheus
      - github-oauth
  namespaceOverride: jenkins

prometheus:
  server:
    replicaCount: 1
    namespaceOverride: observation
    config:
      scrape_configs:
        - job_name: 'webapp'
          static_configs:
            - targets: ['webapp.default.svc.cluster.local:5000']
  alertmanager:
    enabled: false
    namespaceOverride: observation
  pushgateway:
    enabled: false
    namespaceOverride: observation

nodeExporter:
  hostRootFsMount: false
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"
  extraArgs:
    - --path.procfs=/proc
    - --path.sysfs=/sys
    - --web.listen-address=:9100
  namespaceOverride: observation

grafana:
  enabled: true
  adminPassword: 'admin'
  sidecar:
    datasources:
      enabled: true
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.observation.svc.cluster.local
          isDefault: true
  namespaceOverride: observation